#!/bin/bash
# Builds mrdp_cap.h for mrdp_main.c: a random MRDP command stream sized for
# the simulated SoC's 64 KiB ROM, plus the C model's hashes of what it draws.
#   ./mkcap_mrdp.sh [seed] [prims]
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"; M="$HERE/../../lang/c/mrdp"
SEED=${1:-7}; N=${2:-24}
W=64; H=48; FB=0x40100000; ZB=0x40110000; TEX=0x40120000
T="$HERE/build/tools"; mkdir -p "$T"
gcc -O2 -o "$T/test_mrdp_rand" "$M/test_mrdp_rand.c" "$M/mrdp.c" -lm
gcc -O2 -o "$T/mrdp_cap_hash" "$HERE/tools/mrdp_cap_hash.c" "$M/mrdp.c"
MRDP_RAND_N=$N MRDP_RAND_W=$W MRDP_RAND_H=$H MRDP_RAND_FB=$FB MRDP_RAND_ZB=$ZB MRDP_RAND_TEX=$TEX \
MRDP_RAND_TEXMAX=4 "$T/test_mrdp_rand" "$SEED" "$T/cap.bin"
read -r HFB HZ < <("$T/mrdp_cap_hash" "$T/cap.bin" $FB $ZB $W $H)
python3 - "$T/cap.bin" "$HERE/mrdp_cap.h" <<PY
import struct, sys
raw = open(sys.argv[1], 'rb').read(); i = 0; out = []; run = []
def flush():
    if run: out.extend([0x80000000 | len(run)] + run); run.clear()
while i < len(raw):
    t, a, n = struct.unpack_from('<3I', raw, i); i += 12
    if t == 1: run.append(n)
    else:
        flush(); nw = (n + 3) // 4
        out.extend([0x40000000 | nw, a] + list(struct.unpack_from('<%dI' % nw, raw, i))); i += n
flush(); out.append(0)
with open(sys.argv[2], 'w') as f:
    f.write('/* generated by mkcap_mrdp.sh seed $SEED, $N prims -- do not edit */\n')
    f.write('#define CAP_W $W\n#define CAP_H $H\n#define CAP_FB $FB\n#define CAP_ZB $ZB\n')
    f.write('#define CAP_FB_HASH $HFB\n#define CAP_Z_HASH $HZ\n')
    f.write('static const uint32_t cap[%d] = {\n' % len(out))
    for k in range(0, len(out), 8): f.write('    ' + ', '.join('0x%08x' % v for v in out[k:k+8]) + ',\n')
    f.write('};\n')
print('mrdp_cap.h: %d words (%d bytes), fb %s z %s' % (len(out), 4 * len(out), '$HFB', '$HZ'))
PY
