#!/usr/bin/env python3
"""Emit binaries as C arrays of little-endian 32-bit words.

    bin2words.py NAME FILE [NAME FILE ...] > out.h

For each pair: `static const uint32_t NAME_words[]` and `#define NAME_NWORDS`.
Used to embed the audio core's IMEM/DMEM images in game firmware.
"""
import struct
import sys

args = sys.argv[1:]
if not args or len(args) % 2:
    sys.exit(__doc__)
print("/* generated by tools/bin2words.py -- do not edit */")
print("#include <stdint.h>")
for name, path in zip(args[0::2], args[1::2]):
    data = open(path, "rb").read()
    data += b"\0" * (-len(data) % 4)
    words = struct.unpack("<%dI" % (len(data) // 4), data)
    print(f"#define {name.upper()}_NWORDS {len(words)}u")
    print(f"static const uint32_t {name}_words[{max(len(words), 1)}] = {{")
    for i in range(0, len(words), 8):
        print("    " + ", ".join(f"0x{w:08x}u" for w in words[i:i + 8]) + ",")
    if not words:
        print("    0u,")
    print("};")
