#!/usr/bin/env python3
"""Reciprocal seed table for the geom core's RECIPN (rtl/vpu/GeomSetupUnit.v
and lang/c/geom/geom_fixed.c fx_recip_norm(), which must stay bit-identical).

512 entries indexed by the 9 mantissa bits after the leading one, as the N64
RSP's VRCP table is: entry i is
round(2^17 / (1 + (i + 0.5)/512)), a 17-bit value in (2^16, 2^17) stored
without its leading one, so 16 bits. One Newton step in the unit takes the
seed's ~2^-10 relative error to ~2^-21.

Also the NORMF table (geom_rsq_tab / rsq_tab): 1/sqrt, again as the RSP's
VRSQ half of the same ROM does it. Entry {h, k} (h = 0: m in [1,2), h = 1:
m in [2,4), k = the 8 mantissa bits after the leading one) is
round(2^16 / sqrt(m_mid)), m_mid = (1 + (k + 0.5)/256) * (1 + h). No Newton
step: NORMF's result renormalises int8 normals into S17.10, whose own
resolution is 2^-10.

Writes lang/c/geom/geom_rcp_tab.h and rtl/vpu/GeomRcpTab.vh.
"""
import os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
tab = [round(2**17 / (1 + (i + 0.5) / 512)) - 2**16 for i in range(512)]
assert all(0 <= t < 2**16 for t in tab)
rsq = [round(2**16 / ((1 + (k + 0.5) / 256) * (1 + h)) ** 0.5) for h in (0, 1) for k in range(256)]
assert all(2**15 < t < 2**16 for t in rsq)
hdr = "/* Generated by tools/gen_rcp_tab.py -- do not edit. RECIPN seed table:\n" \
      " * entry i = round(2^17 / (1 + (i + 0.5)/512)) - 2^16. */\n" \
      "#ifndef GEOM_RCP_TAB_H\n#define GEOM_RCP_TAB_H\n#include <stdint.h>\n" \
      "static const uint16_t geom_rcp_tab[512] = {\n"
for i in range(0, 512, 8):
    hdr += "    " + ", ".join("0x%04x" % t for t in tab[i:i + 8]) + ",\n"
hdr += "};\n/* NORMF: entry (h << 8) | k = round(2^16 / sqrt((1 + (k + 0.5)/256) * (1 + h))) */\n"
hdr += "static const uint16_t geom_rsq_tab[512] = {\n"
for i in range(0, 512, 8):
    hdr += "    " + ", ".join("0x%04x" % t for t in rsq[i:i + 8]) + ",\n"
hdr += "};\n#endif\n"
open(os.path.join(R, "lang/c/geom/geom_rcp_tab.h"), "w").write(hdr)
vh = "// Generated by tools/gen_rcp_tab.py -- do not edit. RECIPN seed table,\n" \
     "// entry i = round(2^17 / (1 + (i + 0.5)/512)) - 2^16 (see geom_rcp_tab.h).\n" \
     "initial begin\n"
for i, t in enumerate(tab):
    vh += "    rcp_tab[%d] = 16'h%04x;\n" % (i, t)
for i, t in enumerate(rsq):
    vh += "    rsq_tab[%d] = 16'h%04x;\n" % (i, t)
vh += "end\n"
open(os.path.join(R, "rtl/vpu/GeomRcpTab.vh"), "w").write(vh)
print("wrote 512 entries")
