#!/usr/bin/env python3
"""The memory images MIRLO's MIPS SoC (rtl/soc/mirlo_mips.sv) is built with,
as $readmemh files in rtl/soc/init/, and rtl/soc/mirlo_mips_init.svh naming
them by absolute path (Quartus resolves $readmemh next to the file that
calls it; both files are generated, not committed):

  the boot ROM           lang/mips/boot/build/boot.hex
  the geom core's ROMs   lang/c/geom/build/mips/geom.bin: ROM A the first
                         16 KiB, ROM B the 64 KiB from 0x1_0000

The audio core is loaded by the game (lang/c/game/audio_load.c): nothing
here. A missing image gives an empty memory and a warning."""
import os
import struct
import sys

R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
INIT = os.path.join(R, "rtl", "soc", "init")


def words_le(path):
    d = open(path, "rb").read() if os.path.exists(path) else b""
    d += bytes(-len(d) % 4)
    return list(struct.unpack(f"<{len(d) // 4}I", d))


def write(name, lines):
    open(os.path.join(INIT, name), "w").write("".join(lines) if lines else "0\n")
    return os.path.abspath(os.path.join(INIT, name))


def main():
    os.makedirs(INIT, exist_ok=True)
    paths = {}
    boot = os.path.join(R, "lang", "mips", "boot", "build", "boot.hex")
    if not os.path.exists(boot):
        print(f"WARNING: {boot} missing", file=sys.stderr)
    paths["BOOTROM"] = write("boot.hex", open(boot).readlines() if os.path.exists(boot) else [])
    geom = os.path.join(R, "lang", "c", "geom", "build", "mips", "geom.bin")
    if not os.path.exists(geom):
        print(f"WARNING: {geom} missing", file=sys.stderr)
    g = words_le(geom)
    if len(g) > (0x1_0000 + 64 * 1024) // 4:
        sys.exit("geom.bin does not fit ROM A + ROM B")
    if len(g) > 4096 and any(g[4096:0x4000]):
        sys.exit("geom.bin: data between ROM A's end (0x4000) and ROM B (0x1_0000)")
    paths["GEOM_A"] = write("geom_rom_a.hex", [f"{w:08x}\n" for w in g[:4096]])
    paths["GEOM_B"] = write("geom_rom_b.hex", [f"{w:08x}\n" for w in g[0x4000:0x4000 + 16384]])
    svh = ["// generated by tools/mips_inits.py -- do not edit"]
    for k, v in paths.items():
        svh.append(f'`define MIPS_INIT_{k} "{v}"')
    open(os.path.join(R, "rtl", "soc", "mirlo_mips_init.svh"), "w").write("\n".join(svh) + "\n")
    print(f"{INIT}: {len(paths)} images; rtl/soc/mirlo_mips_init.svh")


if __name__ == "__main__":
    main()
